apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness-test
  labels:
    app: nginx-test
spec:
  containers:
  - name: node-app
    image: 656701891231.dkr.ecr.ap-south-1.amazonaws.com/app
    ports:
    - containerPort: 3000
    readinessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-readiness-svc
spec:
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
